// JG67 EFFECTS — Visual enhancements for jg67services.fr
// Do not edit manually — generated by Jarvis

(function () {
  'use strict';

  // JG67 EFFECTS — Detect prefers-reduced-motion
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // ============================
  // JG67 EFFECTS — 1. SCROLL REVEAL
  // ============================
  function initScrollReveal() {
    if (reducedMotion) return;

    // Target h2/h3 titles and grid/columns children in non-hero sections
    const sections = Array.from(document.querySelectorAll('main section'));
    const firstSection = sections[0]; // hero — skip

    sections.forEach(function (section) {
      if (section === firstSection) return;

      // Animate section titles
      section.querySelectorAll('h2, h3').forEach(function (el) {
        if (!el.closest('#devis')) { // skip form section titles
          markReveal(el, 0);
        }
      });

      // Animate direct children of .grid containers with stagger
      section.querySelectorAll('.grid').forEach(function (grid) {
        Array.from(grid.children).forEach(function (child, i) {
          markReveal(child, i * 0.12);
        });
      });

      // Animate masonry columns children (galerie)
      section.querySelectorAll('.columns-1 > div, .columns-1 > article').forEach(function (child, i) {
        markReveal(child, i * 0.08);
      });
    });

    // Set up observer
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.08, rootMargin: '0px 0px -30px 0px' });

    document.querySelectorAll('.reveal').forEach(function (el) {
      observer.observe(el);
    });
  }

  function markReveal(el, delay) {
    // Skip if already in viewport at load time (no flash of invisible content)
    var rect = el.getBoundingClientRect();
    var inViewport = rect.top < window.innerHeight && rect.bottom > 0;
    if (inViewport) return;

    el.classList.add('reveal');
    if (delay > 0) {
      el.style.transitionDelay = delay + 's';
    }
  }

  // ============================
  // JG67 EFFECTS — 3. LIGHTBOX FLUIDE (galerie.html)
  // ============================
  function initLightbox() {
    var lightboxModal = document.getElementById('lightbox-modal');
    var lightboxImg = document.getElementById('lightbox-img');
    if (!lightboxModal || !lightboxImg) return;

    // Only enhance on pages with gallery items
    var galleryWrappers = Array.from(document.querySelectorAll('.cursor-zoom-in'));
    if (galleryWrappers.length === 0) return;

    // Collect images in order
    var images = galleryWrappers.map(function (wrapper) {
      var img = wrapper.querySelector('img');
      return img ? { src: img.src, alt: img.alt || '' } : null;
    }).filter(Boolean);

    if (images.length === 0) return;

    var currentIndex = 0;

    // Add smooth transition to lightbox image
    lightboxImg.style.transition = 'opacity 0.18s ease, transform 0.18s ease';

    // Inject prev/next buttons if not already there
    if (!document.getElementById('lightbox-prev')) {
      var prevBtn = document.createElement('button');
      prevBtn.id = 'lightbox-prev';
      prevBtn.className = 'lightbox-nav';
      prevBtn.setAttribute('aria-label', 'Image précédente');
      prevBtn.innerHTML = '<span class="material-symbols-outlined" style="font-size:28px;line-height:1">chevron_left</span>';

      var nextBtn = document.createElement('button');
      nextBtn.id = 'lightbox-next';
      nextBtn.className = 'lightbox-nav';
      nextBtn.setAttribute('aria-label', 'Image suivante');
      nextBtn.innerHTML = '<span class="material-symbols-outlined" style="font-size:28px;line-height:1">chevron_right</span>';

      lightboxModal.appendChild(prevBtn);
      lightboxModal.appendChild(nextBtn);
    }

    var prevBtn = document.getElementById('lightbox-prev');
    var nextBtn = document.getElementById('lightbox-next');

    function showImage(index) {
      currentIndex = ((index % images.length) + images.length) % images.length;
      lightboxImg.style.opacity = '0';
      lightboxImg.style.transform = 'scale(0.94)';
      setTimeout(function () {
        lightboxImg.src = images[currentIndex].src;
        lightboxImg.alt = images[currentIndex].alt;
        lightboxImg.style.opacity = '1';
        lightboxImg.style.transform = 'scale(1)';
      }, 160);
    }

    // Track which image was clicked
    galleryWrappers.forEach(function (wrapper, i) {
      wrapper.addEventListener('click', function () {
        currentIndex = i;
      });
    });

    // Prev/next buttons
    prevBtn.addEventListener('click', function (e) {
      e.stopPropagation();
      showImage(currentIndex - 1);
    });
    nextBtn.addEventListener('click', function (e) {
      e.stopPropagation();
      showImage(currentIndex + 1);
    });

    // Arrow key navigation (enhanced — Escape already handled inline)
    document.addEventListener('keydown', function (e) {
      if (!lightboxModal.classList.contains('active')) return;
      if (e.key === 'ArrowLeft') showImage(currentIndex - 1);
      if (e.key === 'ArrowRight') showImage(currentIndex + 1);
    });
  }

  // ============================
  // JG67 EFFECTS — 4. HOVER CARDS
  // ============================
  function initHoverCards() {
    // Add .service-card to all bordered rounded cards in main sections
    var cardSelector = [
      '#services .rounded-2xl.border',
      '.grid > .rounded-2xl.border',
      '.grid > a.rounded-2xl',
      'section .rounded-2xl.border.bg-white',
    ].join(', ');

    document.querySelectorAll(cardSelector).forEach(function (card) {
      // Exclude footer, lightbox, form area and nav
      if (card.closest('footer') || card.closest('#devis') || card.closest('#lightbox-modal')) return;
      card.classList.add('service-card');
    });
  }

  // ============================
  // JG67 EFFECTS — 5. NAV STICKY TRANSPARENTE
  // ============================
  function initStickyNav() {
    if (reducedMotion) return;

    var header = document.getElementById('main-header');
    if (!header) return;

    function updateNav() {
      if (window.scrollY < 60) {
        header.classList.add('nav-top');
        header.classList.remove('nav-scrolled');
      } else {
        header.classList.remove('nav-top');
        header.classList.add('nav-scrolled');
      }
    }

    window.addEventListener('scroll', updateNav, { passive: true });
    updateNav(); // run immediately on load
  }

  // ============================
  // JG67 EFFECTS — 6. MENU MOBILE
  // ============================
  function initMobileMenu() {
    var mobileMenu = document.getElementById('mobile-menu');
    var mobileMenuBtn = document.getElementById('mobile-menu-button');
    var closeMenuBtn = document.getElementById('close-menu');
    if (!mobileMenu || !mobileMenuBtn || !closeMenuBtn) return;

    mobileMenuBtn.setAttribute('aria-controls', 'mobile-menu');
    mobileMenuBtn.setAttribute('aria-expanded', 'false');
    closeMenuBtn.setAttribute('aria-label', 'Fermer le menu');
    mobileMenu.setAttribute('aria-hidden', 'true');

    function setMenuOpen(isOpen) {
      mobileMenu.classList.toggle('translate-x-full', !isOpen);
      document.documentElement.classList.toggle('mobile-menu-open', isOpen);
      document.body.classList.toggle('mobile-menu-open', isOpen);
      mobileMenuBtn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
      mobileMenu.setAttribute('aria-hidden', isOpen ? 'false' : 'true');
    }

    mobileMenuBtn.addEventListener('click', function () {
      setMenuOpen(true);
    });

    closeMenuBtn.addEventListener('click', function () {
      setMenuOpen(false);
    });

    mobileMenu.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', function () {
        setMenuOpen(false);
      });
    });

    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && !mobileMenu.classList.contains('translate-x-full')) {
        setMenuOpen(false);
      }
    });

    window.addEventListener('resize', function () {
      if (window.innerWidth >= 768) {
        setMenuOpen(false);
      }
    });

    setMenuOpen(false);
  }

  // ============================
  // JG67 EFFECTS — 7. CURSEUR PERSONNALISÉ
  // ============================
  function initCursor() {
    if (reducedMotion) return;
    // Desktop only — pointer: fine means mouse
    if (!window.matchMedia('(pointer: fine)').matches) return;
    if ('ontouchstart' in window) return;

    var cursor = document.createElement('div');
    cursor.id = 'jg67-cursor';
    document.body.appendChild(cursor);
    document.body.classList.add('jg67-cursor-active');

    var mouseX = window.innerWidth / 2;
    var mouseY = window.innerHeight / 2;
    var curX = mouseX;
    var curY = mouseY;
    var visible = false;

    document.addEventListener('mousemove', function (e) {
      mouseX = e.clientX;
      mouseY = e.clientY;
      if (!visible) {
        visible = true;
        cursor.classList.add('cursor-visible');
        curX = mouseX;
        curY = mouseY;
      }
    });

    document.addEventListener('mouseleave', function () {
      cursor.classList.remove('cursor-visible');
    });
    document.addEventListener('mouseenter', function () {
      if (visible) cursor.classList.add('cursor-visible');
    });

    // Lerp animation loop
    function animateCursor() {
      curX += (mouseX - curX) * 0.15;
      curY += (mouseY - curY) * 0.15;
      cursor.style.left = curX + 'px';
      cursor.style.top = curY + 'px';
      requestAnimationFrame(animateCursor);
    }
    animateCursor();

    // Hover state on interactive elements
    var clickableSelector = 'a, button, [role="button"], input, select, textarea, label, .cursor-zoom-in, .service-card';

    function addHoverListeners() {
      document.querySelectorAll(clickableSelector).forEach(function (el) {
        el.addEventListener('mouseenter', function () { cursor.classList.add('cursor-hover'); });
        el.addEventListener('mouseleave', function () { cursor.classList.remove('cursor-hover'); });
      });
    }

    addHoverListeners();

    // Re-apply for dynamically injected elements (lightbox buttons)
    var domObserver = new MutationObserver(addHoverListeners);
    domObserver.observe(document.body, { childList: true, subtree: true });
  }

  // ============================
  // JG67 EFFECTS — INIT
  // ============================
  function init() {
    initScrollReveal();
    initLightbox();
    initHoverCards();
    initStickyNav();
    initMobileMenu();
    initCursor();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
